# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 07:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_auto_20171110_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='assigned_to',
            field=models.ManyToManyField(related_name='organization_assigned_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Name'),
        ),
    ]
